### ISSUE TITLE
Task Title: Metadata S3

### ISSUE THREAD

**Issue by NhyiraAmofaSekyi** [bicos-io01/Revenue-Sharing-Source#68]

**Comment by Taombawkry** [comment]
{
  "name": "1912.06.0151 :: Woman's Mantle",
  "description": "Woman's cloak of antelope skin (Cobus robertsi, Robert's letje waterbuck, now extinct). Large squares filled with rhombuses, floral ornaments, and triangles. Collected by Eric von Rosen during the Swedish Rhodesia-Congo expedition (1911-1912).",
  "image": "URL_to_image_of_the_artifact",
  "attributes": [
    {
      "trait_type": "Ethnic Group",
      "value": "Twa"
    },
    {
      "trait_type": "Region of Origin",
      "value": "Lake Bangweulu, Zambia"
    },
    {
      "trait_type": "Country of Origin",
      "value": "Zambia, Africa"
    },
    {
      "trait_type": "Material",
      "value": "Antelope Skin"
    },
    {
      "trait_type": "Length",
      "value": "160 cm"
    },
    {
      "trait_type": "Width",
      "value": "145 cm"
    },
    {
      "trait_type": "Collector",
      "value": "Eric von Rosen"
    },
    {
      "trait_type": "Expedition",
      "value": "Swedish Rhodesia-Congo Expedition (1911-1912)"
    },
    {
      "trait_type": "Acquisition Year",
      "value": "1912"
    }
{
"id": "string"
"value": "name_of_artifact"
},
  ]
}
