### ISSUE TITLE
Project wide gas config

### ISSUE THREAD

**Issue by NhyiraAmofaSekyi** [bicos-io01/Revenue-Sharing-Source#79]
should be modular to apply to the interaction scripts

**Comment by Taombawkry** [comment]
Issue is now actually solved: 

[gasConfig
](https://github.com/bicos-io01/Revenue-Sharing-Source/blob/0fc1274b52c8384f61aae46aa5cf91202e2a7d92/packages/dapp/src/app/api/artifactNFT/route.ts#L71)

[see commit details](https://github.com/bicos-io01/Revenue-Sharing-Source/commit/0fc1274b52c8384f61aae46aa5cf91202e2a7d92)

for implementation see [artifactNFT route ](https://github.com/bicos-io01/Revenue-Sharing-Source/blob/0fc1274b52c8384f61aae46aa5cf91202e2a7d92/packages/dapp/src/app/api/artifactNFT/route.ts#L71
)
