### ISSUE TITLE
Ticket gating on oncyber

### ISSUE THREAD

**Issue by NhyiraAmofaSekyi** [bicos-io01/Revenue-Sharing-Source#89]
**Integration/Implementation Category**
Please specify the category this request falls into:
- [X] Frontend
- [X] Smart Contract
- [X] Backend

**Describe the Feature/Functionality**
exhibit gating using ticket nfts.

**Implementation Details**
Event gating using exhibit ticket nfts .

**Use Case and Benefits**
exhibit management 

**Dependencies**
Oncyber configuration.

**Additional context**

**Comment by Taombawkry** [comment]
https://docs.oncyber.io/world-builders-guide/more-advanced-features/privacy-passwords-and-other-gating-mechanisms  

https://discord.com/channels/822523176420376576/1228736968683421716
