### ISSUE TITLE
Ticketing Purchase Testing

### ISSUE THREAD

**Issue by NhyiraAmofaSekyi** [bicos-io01/Revenue-Sharing-Source#92]
*Integration/Implementation Category**
Please specify the category this request falls into:
- [x] Frontend
- [ ] Subgraph
- [ ] Smart Contract
- [ ] Backend

**Describe the Feature/Functionality**
Ensure that the ticket pages for events are fully functional and adhere to the design specifications. The pages should allow users to select tickets, 

**Implementation Details**
The ticket pages should:
- Display all available tickets for an event with descriptions and prices.
- Allow users to select the quantity of tickets.
- Provide a summary of the total cost before proceeding to checkout.

**Use Case and Benefits**
This feature enables users to purchase tickets for events directly through the platform. It enhances user experience and accessibility, making event participation easier and more organized.

**Dependencies**
- Event data API to fetch available tickets and details.
- Payment gateway integration for processing transactions.

**Additional context**

**Comment by Taombawkry** [comment]
@mariojere this is done success and failure components now need to be added to close issue
